### ISSUE TITLE
Feat/Publishing static site on GitHub Pages

### ISSUE THREAD

**Issue by Anugrahsr** [abhijithvijayan/portfolio-cli#6]

**Comment by abhijithvijayan** [comment]
Just use TRAVIS CI to build and push to github pages

- Create a `.travis.yml` file with content
```
language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - 10
git:
  depth: 3
script:
  - yarn run serve
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: out
  target-branch: gh-pages
  on:
    branch: master
```

- Generate a token from [Personal Access Token](https://github.com/settings/tokens)
- Connect [travisci](https://travis-ci.com/) with GitHub account and add the repository
- Supply `GITHUB_TOKEN` field with token generated
- Trigger a Build

![Screenshot from 2019-11-19 13-54-57](https://user-images.githubusercontent.com/34790378/69129449-614cf780-0ad4-11ea-815a-3ec46b51e042.png)
